### ISSUE TITLE
Add Extension to the Gallery

### ISSUE THREAD

**Issue by montanehamilton** [sierpinski/Blitz#11]
Great extension would you be interested in listing this on the gallery so we can use it easily?

https://www.visualstudio.com/integrate/extensions/publish/guidelines

I would be willing to help make it happen if you need?

**Comment by sierpinski** [comment]
Yes it is already there! I accidentally deleted the link!!! Whoops! Thanks for catching that! [It is right here!](https://marketplace.visualstudio.com/items?itemName=sierpinski.blitz-allpulls-extension) I am so glad you like the extension. I originally just made an app and then smart folks like you suggested making an extension so I converted it!
