### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by montanehamilton** [sierpinski/Blitz#12]
So installing the extension is great through the gallery. Can we add a dashboard widget that shows at least the number of open? That would be great.

I'm not sure what's involved in a dashboard widget but would be willing to help learn if you don't know too..

**Comment by sierpinski** [comment]
That sounds fun. I'd love the help. I haven't done it before, either! Let's look into it. I might get some time tonight or tomorrow night to start reading about it. I'll put any code I come up with in the repo. Feel free to send a pull request if you beat me to it.

**Comment by sierpinski** [comment]
Oops, accidentally clicked close and comment instead of comment!

**Comment by montanehamilton** [comment]
https://www.visualstudio.com/en-us/integrate/extensions/develop/add-dashboard-widget

**Comment by sierpinski** [comment]
Awesome link. I'll take a look right now.

**Comment by montanehamilton** [comment]
Looks like JS and HTML mostly! Been busy dealing with problem in my real work! :(

**Comment by sierpinski** [comment]
No problem. Figuring out a parse issue on my manifest.json file. Once I do, I should be able to test out my first effort. Will update here when I have news.

**Comment by sierpinski** [comment]
Thinks are going well now, I have added the widget! Right now it is just a flat count. I need to make sure it is a link that takes you to the pull request list.

**Comment by sierpinski** [comment]
If you go to your team dashboard, you should see the widget when you click the + sign. It is just a count of your active pull requests. But, it's a start.

**Comment by sierpinski** [comment]
Awesome! I got the link working! So, now you get a count and it takes you to the extension!

**Comment by sierpinski** [comment]
I'll update the code on here as soon as I can.

**Comment by montanehamilton** [comment]
![capture](https://cloud.githubusercontent.com/assets/8663799/15266012/cbcaafc4-1953-11e6-9405-33c79bd77e1b.PNG)
If we could match this style it'd be a great start.

**Comment by montanehamilton** [comment]
Rocks!
![capture](https://cloud.githubusercontent.com/assets/8663799/15266024/628c3bbc-1954-11e6-8611-3185b1afc3e4.PNG)

**Comment by sierpinski** [comment]
Nice... let me check on that style/coloring. I tried it once and it didn't work. I'll dive a little deeper. I moved "Pull Requests" under the 2 and it looks good.

**Comment by sierpinski** [comment]
Code updated.

**Comment by montanehamilton** [comment]
Looks great, my colleague and I might have some pull requests if we come up with some improvements but this is awesome. Only thing I'm wondering about is link to open new window or not? That default changes one opens in same window. Styling wise maybe get rid of the underline on the active state. Looking forward to looking more at the code too!

**Comment by sierpinski** [comment]
I updated the colors.
![image](https://cloud.githubusercontent.com/assets/9721083/15266085/7fa95334-1967-11e6-8e4b-84ac3eea1987.png)

**Comment by montanehamilton** [comment]
Oooh! I see, love it. Love how these changes just update automatically when the extension is installed!

**Comment by sierpinski** [comment]
I removed the underline styling on the a hrefs. I love that, too. Also kind of scary, because I'm updating everyone live even with my breaking changes!

**Comment by sierpinski** [comment]
Let me take a look at the link opening in new window idea. I think I'd prefer not to open a new window, too.

**Comment by montanehamilton** [comment]
Ok I'm out for the night, this is awesome and makes the heart of your extension easier to get to!

**Comment by sierpinski** [comment]
Thanks for the awesome idea! Night! I'll do a couple tweaks and close this issue.

**Comment by sierpinski** [comment]
The widget is now opening on the same page and everything is looking great! I'll close this one out! Thanks for the great ideas and help!
