### ISSUE TITLE
missing file on TFS2015U2 on premises, loading PRs never ends

### ISSUE THREAD

**Issue by nilleb** [sierpinski/Blitz#13]
The 'Active Pull Requests' page keeps loading undefinitely.
If I have a look at the network exchanges using the Chrome developer tools, I see a 404 for Bundling.js

The TFS on premises instance is a 2015U2

**Comment by sierpinski** [comment]
Okay, I'll take a look as soon as I can. Sorry it's not working. I've only been testing on VSTS. So, I'm glad to get feedback from someone on-prem.

**Comment by nilleb** [comment]
No need to be sorry. I'm sure it works great on VSTS. Thanks for your time.

**Comment by chrisvanderpennen** [comment]
This is fixed in the latest VSS.SDK.js, but then you'll just run into the next on-prem issue - because the content iframe is sandboxed and doesn't set `allow-same-origin`, the handle request links open a new window with `null` origin, which then dies horribly when it can't access `document.cookie`.

Unfortunately I suspect that's not fixable.  Plugin is still useful as a dashboard though.

**Comment by sierpinski** [comment]
Hmm... I will make sure I update the vss.sdk.js. Hmm, that link issue sounds tricky to fix.

**Comment by sierpinski** [comment]
Thanks @chrisvanderpennen for the info on this. I was at a loss.

**Comment by sierpinski** [comment]
If either of you could check, when you click the pull request widget does it link properly to the extension? If it does, maybe changing my a href's from _blank to _parent might work?

**Comment by sierpinski** [comment]
For @chrisvanderpennen Using chrometools, could you inspect the link and change the _blank to _parent and see if the link works? If so, I'll correct that.

**Comment by chrisvanderpennen** [comment]
@sierpinski `_parent` and `_top` both result in a new tab with `document.origin === "null"`

e: also i snuck an ssl binding onto the on-premise install. didn't help sadly.  would you mind inspecting the iframe on vso and pasting the content of the `sandbox` attribute?

**Comment by sierpinski** [comment]
Thanks for trying @chrisvanderpennen I grabbed the iframe and am placing it here:

```
<iframe frameborder="0" src="https://sierpinski.gallery.vsassets.io/_apis/public/gallery/publisher/sierpinski/extension/blitz-allpulls-extension/0.8.5/assetbyname/blitzallpulls.html" class="external-content-iframe" id="externalContentHost23" name="externalContentHost23" style="display: inline;">
...My extension goes here...
</iframe>
```

I don't see sandbox explicitly mentioned.

**Comment by sierpinski** [comment]
@nilleb I have updated the vss.sdk so you will hopefully be able to see the pull requests in the extension now.

**Comment by chrisvanderpennen** [comment]
> sierpinski.gallery.vsassets.io

That explains it.  VSO isn't sandboxing the iframe because it's loaded from another domain anyway - which means any windows it opens are just regular windows.

**Comment by StandBackBurrito** [comment]
Is there any resolution on the `document.origin` issue?

**Comment by sierpinski** [comment]
Not yet. I am receiving some error logs now, so they might give me some insight. Any advice is welcome on the issue while I try to snoop out the problem.

**Comment by sierpinski** [comment]
I've attempted to fix the issue. If anybody with on-prem. could check to see if the links work, I would appreciate it.

**Comment by sierpinski** [comment]
I fixed it!!! Please use the most up-to-date version of my extension from the Marketplace! :) Finally!!!

**Comment by nilleb** [comment]
great! thanks!
