### ISSUE TITLE
Widget on On-Prem Not Available

### ISSUE THREAD

**Issue by jmesserer** [sierpinski/Blitz#14]
I don't see any additional PR widgets available after install (on-prem).

**Comment by sierpinski** [comment]
Okay, let me take a look. If it worked, when you clicked add on a dashboard it would look like this:
![image](https://cloud.githubusercontent.com/assets/9721083/15759877/bda262bc-28de-11e6-86cc-d7dbf6289a64.png)

This is the second on-prem issue I've been told about. The other involved links to pull requests not opening properly when clicked on the pull request table. I know they are updating the VSTS extension documentation frequently, so there might be some guidance there. I'll update you if I discover anything. Please do the same if you figure it out. It may be time for me to run a local TFS server at home, so I can test the extension in an on-prem environment... Thanks for letting me know.

**Comment by jmesserer** [comment]
Thanks. I'm experiencing the other on-prem issue that's mentioned.

![image](https://cloud.githubusercontent.com/assets/304973/15761050/d5cc1b10-28db-11e6-82f6-2e8f4c965dab.png)

**Comment by Hunter21007** [comment]
Same issue also on-prem. (TFS 2015 Update2)
Is there a log somewhere? where i could try to look on?

**Comment by sierpinski** [comment]
I don't have an error log. I'm sorry again about the on-prem issues. It seems to be doing well online. I'll see if I can add application insights to catch these errors. Once I do, I'll paste the logs here for you to check out.

**Comment by michael-baker** [comment]
I have an issue with on-prem 2015 Update 2 - with the "All Pull Requests" tab just being blank despite having requests in more than one repo. 
Should I open a new issue for this or do you think it's related to this problem?

**Comment by sierpinski** [comment]
Thank you all for reporting these issues. You do not need to open a new issue. These are all related to on-prem concerns I need to look into in my extension. If I cannot code around these issues, I can modify the extension to be VSTS only but I want to work on-prem so hopefully I will find an answer.

**Comment by Hunter21007** [comment]
Today run Update 3, widget is now available and working.

:)

**Comment by sierpinski** [comment]
@Hunter21007 that is amazing news!!! Thank you for telling me! Does the whole extension work? Particularly, does it list your pull requests and if you click the link does it properly open the pull request link in a new window or is that still broken? Thank you again for the fantastic news!!

**Comment by Hunter21007** [comment]
- The widget Can be placed on dashboard, and Displays Count of prs
- the Click on it leads to the list of prs
- the Click on handle request opens the view with prs in new window but nod data is displayed. And the new window displays errors due to missing login data

**Comment by Hunter21007** [comment]
Extension ver 0.8.8

**Comment by Hunter21007** [comment]
jk-1260-vminfo
BranchUpdated ByLast UpdatedBehindAhead
Close [x]
Error(s):

401: 401: error
TFS.WebApi.Exception: 401: error
    at k (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:375)
    at http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2955
    at d (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:635)
    at http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/corejs?v=ITI0eYHCCehqqjk6JTyPaR5R793ETLoY2_Lqz191Pyo1:64:2888
    at l (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8122)
    at http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:8348
    at t.when (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:3780)
    at t.u.promiseDispatch (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:2824)
    at http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:1649
    at MessagePort.t (http://tfs.msg-sfb.net/tfs/_static/tfs/Dev14.M102/_scripts/TFS/min/q.js:27:5773)
Session Id: 4a7c21ee-30d8-4af2-a572-feb7edcecf79

**Comment by sierpinski** [comment]
Hi all. I've tried to modify the links on the pull request page. They are now constructed out of API calls and should open in the same window. If someone on-prem. could please check to see if this changed the links, I would be ever so grateful!

**Comment by michael-baker** [comment]
I can test this on my on-prem install. Is the latest package published to the market place or should I install from sources?

**Comment by sierpinski** [comment]
It is up-to-date on the Marketplace, thank you!

**Comment by Hunter21007** [comment]
Will Test it, thanks.

**Comment by michael-baker** [comment]
Given it a test on my on-prem install. When using the FQDN of my install I no longer get a white page when following a PR link so this would appear to be fixed.

**Comment by sierpinski** [comment]
Fantastic! I am elated! Thank you for testing for me. I appreciate it.

**Comment by Hunter21007** [comment]
Works!

**Comment by sierpinski** [comment]
Yes!!!! Wahoo!! Thank you!!
