### ISSUE TITLE
Branch Blitz - Showing Master

### ISSUE THREAD

**Issue by pcoombe** [sierpinski/Blitz#18]
We are using a gitflow similar workflow, with development and master branches.
Im assuming as we have development set as the default branch that its causing problems, because it is not showing any development branches.

![image](https://cloud.githubusercontent.com/assets/15317948/19795559/50db8992-9d28-11e6-9ae3-750c8c8aa05a.png)

**Comment by sierpinski** [comment]
Yes, I coded it to ignore the default branch (in your case, not master)! :) You caught my trick... I could filter out branches named "master" instead. Sorry about that! Would you like that filter instead?

**Comment by sierpinski** [comment]
Okay, I updated the extension to filter on the name "master" instead of "isbaseversion" so please let me know if it works. Version 0.5.4.
