### ISSUE TITLE
Handle Request "button" access issues/ideas

### ISSUE THREAD

**Issue by Russweb** [sierpinski/Blitz#19]
So the "Handle Request" button thing is a little clunky.

1) Its on the far right of the grid. Not the natural expected left for action.
2) Why the button? Its really just a link to the PR, right? Nothing more?
I think it would be far better for space utilization to drop that column altogether and allow access by either click on the row in general, or turning the request number into a hyperlink to the request.
3) the button is not even visible if you increase your resolution. It goes offscreen.  Doing #2, would eliminate that concern.

**Comment by sierpinski** [comment]
Russweb, these are great ideas. As soon as I get a chance I'll take a look.

**Comment by sierpinski** [comment]
As of version 0.9.8, the rows are now clickable. Thanks for this idea. Hopefully, users will like the change.
