### ISSUE TITLE
Persistent XSS vounerability

### ISSUE THREAD

**Issue by J-Sek** [sierpinski/Blitz#20]
Anyone in the team can drop "<script>alert('!')</script>" into the PR description and successfully sabotage access to the extension tab. More importantly if it is installed on corpo-instance (on premise), you have no guarantee that someone will not try to hack other developers.

**Comment by sierpinski** [comment]
I hadn't considered that XSS attacks could be passed in pull request descriptions. Wow! Thank you for pointing this out!!! Will take a look as soon as I can.

**Comment by sierpinski** [comment]
Okay, I believe I have prevented XSS vulnerability, now. Will you please verify, if possible. All of my tests are passing and the extension appears to be protected, but would appreciate the help testing. I won't close, hoping you can double check for me. Version 0.9.4 of the extension forward.

**Comment by J-Sek** [comment]
Great!
It is not possible to execute script from PR title now.

In the source code I can still see lots of places that create HTML from concatenated strings, but none of the properties can contain `<script>`. I can only suggest using templating language (e.g. [Pug](https://pugjs.org)) as a future improvement.

**Comment by sierpinski** [comment]
Thank you, I've never used Pug, thanks for the suggestion!
