### ISSUE TITLE
Can't open PRs in new tab anymore

### ISSUE THREAD

**Issue by aueelis** [sierpinski/Blitz#24]
I know the intention of #19 was to remove the ugly button, but now I can't open PRs in a new tab anymore.

**Comment by sierpinski** [comment]
Whoops! Let's see if I can fix it.

**Comment by sierpinski** [comment]
Ok, need to clean up the formatting, but I made the IDs clickable, so you can open in new window. Sorry for the inconvenience!

**Comment by sierpinski** [comment]
@aueelis Did that fix the issue for you?

**Comment by aueelis** [comment]
Yep. It's fixed. Thank you very much!
