### ISSUE TITLE
Hyperlinks don't work if TFS url contains spaces

### ISSUE THREAD

**Issue by braydie** [sierpinski/Blitz#26]
I'm using TFS on prem and have noticed that the hyperlinks to pull requests are broken if the team collection contains spaces

**Comment by sierpinski** [comment]
I don't have on-prem access. Is it possible to provide a url that is broken and the correct url?

I'm guessing I'm missing some url encoding, but being able to see the links will help.

**Comment by braydie** [comment]
No worries. Clicking the pull request works correctly, it is just the hyperlink from the ID that does not work correctly.

Example URLs:

`http://vsomdteamfs:8080/tfs/Isle%20of%20Man%20Gov/eServices/_git/949d8389-95c6-4c67-a848-7e30a1f90067/pullRequest/225`

And the URL that appears on the ID is `http://vsomdteamfs:8080/tfs/Isle`

**Comment by braydie** [comment]
Reason for accessing the link via the ID is that it's a proper `a` tag and can be opened in a new tab

**Comment by sierpinski** [comment]
I updated this just now to version 1.0.5 and it should fix the link. Please let me know when you get a chance to test it.  Appreciate the bug hunting!
