### ISSUE TITLE
merge state in PR overview have wrong status

### ISSUE THREAD

**Issue by fotopixel** [sierpinski/Blitz#27]
Hi we are using this app now and i see that the state of 'merge status' is wrong or it comes from a place which is not correct. 

What I expect is that is show the status of merging the PR to target branch (in my case Development) but the PR is still active and there is no merge to this target.

![image](https://user-images.githubusercontent.com/7202441/43137696-c45e24fc-8f4c-11e8-94bc-e0c6b6db3f38.png)

what can we do to get the correct state of the 'merge status'.

**Comment by sierpinski** [comment]
Hi, the merge status is pulled from the pull request object in VSTS and it is hard-coded to "3". It is possible... likely? that the merge statuses have changed since I first wrote the extension. I'll see if I can figure out whether there might have been changes I'm missing so I can improve that.

**Comment by fotopixel** [comment]
i think we can close this bug... i find now what this state is displaying ... and you did it correct ... 

it is the merge state of the PR ... if there is a conflict you display Failed... and if there is no conflict you display Succeeded.

But it would be better to change the label 'Failed' to 'Conflicts'

**Comment by sierpinski** [comment]
Thanks for checking this! I'll create a new feature request to change the text,
