### ISSUE TITLE
SecurityError and TypeError in v1.0.10

### ISSUE THREAD

**Issue by MDendura** [sierpinski/Blitz#29]
Since the update to v1.0.10 this morning the list of active pull requests no longer works in my TFS2018 system under Firefox 61.0.2, Edge 42.17134.1.0, Chrome 68.0.3440.106 or IE 11.228.17134.0.

The user is presented with a blank list:

![image](https://user-images.githubusercontent.com/917692/44399506-c6b3e080-a53f-11e8-98f3-0914caa4c313.png)

The browser console gives the following error messages:

![image](https://user-images.githubusercontent.com/917692/44399571-05e23180-a540-11e8-9f74-6d852de4c6cb.png)

**Comment by sierpinski** [comment]
If possible, please update to version 1.0.33. I just released it and it turns off app insights, which should fix the first error. Please follow-up to let me know if it does.

Edit: And sorry for breaking it.

**Comment by MDendura** [comment]
This now works as expected. Thanks!

**Comment by sierpinski** [comment]
Yay! Sorry for any inconvenience.
