### ISSUE TITLE
Invalid menu items appears in VSTS when "Active Pull Request" is active.

### ISSUE THREAD

**Issue by johnallers** [sierpinski/Blitz#3]
Installed the extension in a VSTS project.

Menu items are correct when "Active Pull Request" is inactive:

![Inactive](https://cloud.githubusercontent.com/assets/334458/14936489/f7286032-0ebb-11e6-8aaf-895f4fa10359.PNG)

But invalid menu items appear when it is active:

![Active](https://cloud.githubusercontent.com/assets/334458/14936487/ef000806-0ebb-11e6-8eab-d8e8bb19d124.png)

**Comment by johnallers** [comment]
Actually, I'm seeing this with other extensions that use the Code hub, so it must be a VSTS issue.

**Comment by sierpinski** [comment]
Thanks for noticing this! It frustrated me when I saw this, too. I'll definitely fix this if I discover the right setting.
