### ISSUE TITLE
Show repository

### ISSUE THREAD

**Issue by pascalberger** [sierpinski/Blitz#4]
An additional column showing the repository for which the PR is open would be helpful.

**Comment by sierpinski** [comment]
This is a great idea. I've updated the design of the extension and it would be natural to add this column. I'll comment here as soon as it is ready.

**Comment by sierpinski** [comment]
I had this coded in initially, but it slowed down the page load, since I made the call before loading any assets. So, I removed it. Let's add it back in after page load so it doesn't slow down the UI too much.

**Comment by sierpinski** [comment]
This is now added as of version 0.4.3.
